# Generated by Django 5.0.6 on 2024-06-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingeniero', models.CharField(max_length=100)),
                ('victoria', models.IntegerField()),
                ('años', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Componente',
        ),
        migrations.AddField(
            model_name='equipo',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.piloto'),
        ),
    ]
